<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="My test suite" duration-ms="185" started-at="2009-08-19T18:43:50Z" finished-at="2009-08-19T18:43:50Z">
    <groups>
    </groups>
    <test name="my test" duration-ms="185" started-at="2009-08-19T18:43:50Z" finished-at="2009-08-19T18:43:50Z">
      <class name="May14.Test1">
        <test-method status="FAIL" signature="m2()[pri:0, instance:May14.Test1@4de8b406]" name="m2" duration-ms="20" started-at="2009-08-20T00:13:50Z" finished-at="2009-08-20T00:13:50Z">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
	at May14.Test1.m2(Test1.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m2 -->
        <test-method status="PASS" signature="m3(java.lang.String, java.lang.String)[pri:0, instance:May14.Test1@4de8b406]" name="m3" duration-ms="1" started-at="2009-08-20T00:13:50Z" finished-at="2009-08-20T00:13:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://google.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[60]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m3 -->
        <test-method status="PASS" signature="m1()[pri:0, instance:May14.Test1@4de8b406]" name="m1" duration-ms="1" started-at="2009-08-20T00:13:50Z" depends-on-methods="May14.Test1.m2" finished-at="2009-08-20T00:13:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- m1 -->
      </class> <!-- May14.Test1 -->
    </test> <!-- my test -->
  </suite> <!-- My test suite -->
</testng-results>
